### ISSUE TITLE
Integration tests in Dockerless mode

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/fanal#75]
Add integration tests to communicate with Docker Registry

**Comment by simar7** [comment]
I've been looking into this and found some oddities:

The current test images we're using are not the ones found on docker hub. For instance:

1. Alpine image 3.10.2 that we use doesn't seem to exist on docker hub, instead 3.10.4 exists.
2. Amazon Linux version 2 seems to have a different OS version.
```
We have :analyzer.OS{Name:"2 (Karoo)", Family:"amazon"}
Docker Hub :analyzer.OS{Name:"AMI release 2018.03", Family:"amazon"}
```

How were the current images created? Should we revise them? Or should we instead have a separate list of test cases for docker less mode since the expectations might change tomorrow depending on if images get removed from docker hub.

This also raises another question, what should we do if we can't find images on docker hub anymore? Should the test fail?

**Comment by knqyf263** [comment]
I didn't change those images at all, but an image with the same tag is updated continuously. A tag, `alpine:3.10` points to `alpine:3.10.2` today, but it may point `alpine:3.10.3` tomorrow. I exported all of those images a few months ago. These images should be different from images in Docker Hub. Then, I uploaded those images to my repository.
https://hub.docker.com/u/knqyf263

These images are completely the same as [this repository](https://github.com/aquasecurity/trivy-test-images). We can use these images in Docker Hub. They will not be updated until I do that.
